### ISSUE TITLE
Problem with comments highlighting

### ISSUE THREAD

**Issue by hjmarseille** [reekers/language-vbscript#4]
Hi, I noticed there's a problem with comment highlighting. VBScript comments are made with a single quote ( ' ) and as far as I know, they're single line. However, it seems that the highlighting is considering them as block comments so you have to start and end the comment with a single quote. So if I have something like:
' This is an comment
dim variable
variable = 1
' This is another comment

the first comment and the entire code block is highlighted as comment and the second comment is left colored as code.

**Comment by reekers** [comment]
Hey there. Sorry about the late reaction, been a bit too busy... 

I'm unable to reproduce this however. Can you reproduce this and and me specifics?

**Comment by reekers** [comment]
Not reproducable
